import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';

const rawUrl = process.env.MOBU_RACE_WS_URL;
if (!rawUrl) {
  throw new Error('MOBU_RACE_WS_URL is required (for example: wss://mobu-race-realtime.<account>.workers.dev/ws).');
}

let websocketUrl;
try {
  const url = new URL(rawUrl);
  if (url.protocol === 'https:') url.protocol = 'wss:';
  if (url.protocol === 'http:') url.protocol = 'ws:';
  if (!['ws:', 'wss:'].includes(url.protocol)) throw new Error('must use ws, wss, http, or https');
  if (!url.pathname || url.pathname === '/') url.pathname = '/ws';
  websocketUrl = url.href;
} catch (error) {
  throw new Error(`Invalid MOBU_RACE_WS_URL: ${error.message}`);
}

await rm('dist', { recursive: true, force: true });
await mkdir('dist', { recursive: true });
await cp('public', 'dist', { recursive: true });
// Directory entries survive direct navigation and refresh on Pages. Asset
// URLs in the shared shell are root-relative, including on trailing-slash URLs.
// Keep route metadata in the delivered HTML (social crawlers often skip JS).
const routeMetadata = {
  live: {
    title: 'Mobu Race Live — Multiplayer 3D Racing',
    description: 'Join a live Mobu Race: a cozy multiplayer 3D race with chubby characters, dramatic finishes, and friends watching together.',
  },
  moon: {
    title: 'Mid-Autumn Festival Mobu Race 🏮',
    description: 'Celebrate Tết Trung Thu with Mobu Race: a cozy moonlit multiplayer race with glowing Vietnamese lanterns, a harvest moon, and dramatic finishes.',
  },
};

function setMeta(html, attribute, key, value) {
  const pattern = new RegExp(`(<meta ${attribute}="${key}" content=")[^"]*(")`);
  if (!pattern.test(html)) throw new Error(`Could not find ${attribute}=${key} in index.html`);
  return html.replace(pattern, `$1${value}$2`);
}

for (const [entry, metadata] of Object.entries(routeMetadata)) {
  await mkdir(`dist/${entry}`, { recursive: true });
  let html = await readFile('dist/index.html', 'utf8');
  html = html.replace(/<title>[^<]*<\/title>/, `<title>${metadata.title}</title>`);
  html = html.replace('<link rel="canonical" href="/" />', `<link rel="canonical" href="/${entry}" />`);
  for (const [attribute, key] of [
    ['name', 'description'],
    ['property', 'og:title'],
    ['property', 'og:description'],
    ['name', 'twitter:title'],
    ['name', 'twitter:description'],
  ]) {
    const value = key.endsWith('description') ? metadata.description : metadata.title;
    html = setMeta(html, attribute, key, value);
  }
  await writeFile(`dist/${entry}/index.html`, html);
}
await writeFile('dist/config.js', `// Generated by scripts/build-pages.mjs\nwindow.MOBU_RACE_WS_URL = ${JSON.stringify(websocketUrl)};\n`);
console.log(`Built Pages assets with realtime endpoint: ${websocketUrl}`);
