import { copyFile, cp, mkdir, rm, writeFile } from 'node:fs/promises';

const rawUrl = process.env.MOBU_RACE_WS_URL;
if (!rawUrl) {
  throw new Error('MOBU_RACE_WS_URL is required (for example: wss://mobu-race-realtime.<account>.workers.dev/ws).');
}

let websocketUrl;
try {
  const url = new URL(rawUrl);
  if (url.protocol === 'https:') url.protocol = 'wss:';
  if (url.protocol === 'http:') url.protocol = 'ws:';
  if (!['ws:', 'wss:'].includes(url.protocol)) throw new Error('must use ws, wss, http, or https');
  if (!url.pathname || url.pathname === '/') url.pathname = '/ws';
  websocketUrl = url.href;
} catch (error) {
  throw new Error(`Invalid MOBU_RACE_WS_URL: ${error.message}`);
}

await rm('dist', { recursive: true, force: true });
await mkdir('dist', { recursive: true });
await cp('public', 'dist', { recursive: true });
// Directory entries survive direct navigation and refresh on Pages. Asset
// URLs in the shared shell are root-relative, including on trailing-slash URLs.
for (const entry of ['live', 'moon']) {
  await mkdir(`dist/${entry}`, { recursive: true });
  await copyFile('dist/index.html', `dist/${entry}/index.html`);
}
await writeFile('dist/config.js', `// Generated by scripts/build-pages.mjs\nwindow.MOBU_RACE_WS_URL = ${JSON.stringify(websocketUrl)};\n`);
console.log(`Built Pages assets with realtime endpoint: ${websocketUrl}`);
